language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

branches:
  only:
    - master

install:
  - pip install -U pip wheel tox-travis
  - pip install -r requirements/dev.txt

script: tox
